{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOf0F+wn4EiETC4W4KdIr8f"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["Python uses special objects called exceptions to manage errors that arise during a program’s execution. Whenever an error occurs that makes Python\n","unsure what to do next, it creates an exception object. If you write code\n","that handles the exception, the program will continue running. If you don’t\n","handle the exception, the program will halt and show a traceback, which\n","includes a report of the exception that was raised.\n","\n","Exceptions are handled with try-except blocks. A try-except block asks\n","Python to do something, but it also tells Python what to do if an exception is raised. When you use try-except blocks, your programs will continue\n","running even if things start to go wrong. Instead of tracebacks, which can\n","be confusing for users to read, users will see friendly error messages that\n","you write."],"metadata":{"id":"y4jSh9RngO39"}},{"cell_type":"markdown","source":["### Handling the ZeroDivisionError Exception\n","Let’s look at a simple error that causes Python to raise an exception. You\n","probably know that it’s impossible to divide a number by zero, but let’s ask\n","Python to do it anyway:\n","`division_calculator.py`\n"],"metadata":{"id":"38F4CZeWgQbV"}},{"cell_type":"code","source":["print(5/0)"],"metadata":{"id":"lSgP6dfNgs5V"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Of course Python can’t do this, so we get a traceback:\n","```\n","Traceback (most recent call last):\n"," File \"division_calculator.py\", line 1, in <module>\n"," print(5/0)\n"," ZeroDivisionError: division by zero        (#1)\n","```\n","The error reported at **#1** in the traceback, ZeroDivisionError, is an exception object. Python creates this kind of object in response to a situation\n","where it can’t do what we ask it to. When this happens, Python stops the\n","program and tells us the kind of exception that was raised. We can use this\n","information to modify our program. We’ll tell Python what to do when this\n","kind of exception occurs; that way, if it happens again, we’re prepared."],"metadata":{"id":"gftovOJlg86U"}},{"cell_type":"markdown","source":["### Using try-except Blocks\n","When you think an error may occur, you can write a try-except block to\n","handle the exception that might be raised. You tell Python to try running\n","some code, and you tell it what to do if the code results in a particular kind\n","of exception.\n","\n","Here’s what a try-except block for handling the ZeroDivisionError exception looks like:\n"],"metadata":{"id":"4wjjl6XNhO-8"}},{"cell_type":"code","source":["try:\n","  print(5/0)\n","except ZeroDivisionError:\n","  print(\"You can't divide by zero!\")"],"metadata":{"id":"5eBWq9AlhVgD"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["We put print(5/0), the line that caused the error, inside a try block. If\n","the code in a try block works, Python skips over the except block. If the code\n","in the try block causes an error, Python looks for an except block whose\n","error matches the one that was raised and runs the code in that block.\n","\n","In this example, the code in the try block produces a ZeroDivisionError,\n","so Python looks for an except block telling it how to respond. Python then\n","runs the code in that block, and the user sees a friendly error message\n","instead of a traceback:\n","```\n","You can't divide by zero!\n","```\n","If more code followed the try-except block, the program would continue\n","running because we told Python how to handle the error. Let’s look at an\n","example where catching an error can allow a program to continue running."],"metadata":{"id":"Vl49MpSGhccr"}},{"cell_type":"markdown","source":["### Using Exceptions to Prevent Crashes\n","Handling errors correctly is especially important when the program has\n","more work to do after the error occurs. This happens often in programs\n","that prompt users for input. If the program responds to invalid input appropriately, it can prompt for more valid input instead of crashing.\n","\n","Let’s create a simple calculator that does only division:\n"],"metadata":{"id":"bAv0RcF9hiKz"}},{"cell_type":"code","source":["print(\"Give me two numbers, and I'll divide them.\")\n","print(\"Enter 'q' to quit.\")\n","\n","while True:\n","  first_number = input(\"\\nFirst number: \")    #1\n","  if first_number == 'q':\n","    break\n","  second_number = input(\"Second number: \")    #2\n","  if second_number == 'q':\n","    break\n","  answer = int(first_number) / int(second_number)   #3\n","  print(answer)"],"metadata":{"id":"tkGgq_XphmVj"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["This program prompts the user to input a first_number **#1** and, if the\n","user does not enter q to quit, a second_number **#2**. We then divide these two\n","numbers to get an answer **#3**. This program does nothing to handle errors,\n","so asking it to divide by zero causes it to crash:\n","```\n","Give me two numbers, and I'll divide them.\n","Enter 'q' to quit.\n","\n","First number: 5\n","Second number: 0\n","Traceback (most recent call last):\n","  File \"division_calculator.py\", line 9, in <module>\n","  answer = int(first_number) / int(second_number)\n","ZeroDivisionError: division by zero\n","```\n","It’s bad that the program crashed, but it’s also not a good idea to let\n","users see tracebacks. Nontechnical users will be confused by them, and in\n","a malicious setting, attackers will learn more than you want them to know\n","from a traceback. For example, they’ll know the name of your program\n","file, and they’ll see a part of your code that isn’t working properly. A skilled\n","attacker can sometimes use this information to determine which kind of\n","attacks to use against your code."],"metadata":{"id":"WqYqb14ch0KS"}},{"cell_type":"markdown","source":["### The else Block\n","We can make this program more error resistant by wrapping the line that\n","might produce errors in a try-except block. The error occurs on the line\n","that performs the division, so that’s where we’ll put the try-except block.\n","This example also includes an else block. Any code that depends on the try\n","block executing successfully goes in the else block:"],"metadata":{"id":"zKcUHnQXiWxB"}},{"cell_type":"code","source":["--snip--\n","while True:\n","  --snip--\n","  if second_number == 'q':\n","    break\n","  try:    #1\n","    answer = int(first_number) / int(second_number)\n","  except ZeroDivisionError:   #2\n","    print(\"You can't divide by 0!\")\n","  else:   #3\n","    print(answer)"],"metadata":{"id":"Lh1-NmpFiamv"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["We ask Python to try to complete the division operation in a try\n","block **#1**, which includes only the code that might cause an error. Any\n","code that depends on the try block succeeding is added to the else block.\n","In this case if the division operation is successful, we use the else block to\n","print the result **#2**.\n","\n","The except block tells Python how to respond when a ZeroDivisionError\n","arises **#3**. If the try block doesn’t succeed because of a division by zero\n","error, we print a friendly message telling the user how to avoid this\n","kind of error. The program continues to run, and the user never sees\n","a traceback:\n","```\n","Give me two numbers, and I'll divide them.\n","Enter 'q' to quit.\n","\n","First number: 5\n","Second number: 0\n","You can't divide by 0!\n","First number: 5\n","Second number: 2\n","2.5\n","\n","First number: q\n","```\n","The try-except-else block works like this: Python attempts to run the\n","code in the try block. The only code that should go in a try block is code\n","that might cause an exception to be raised. Sometimes you’ll have additional code that should run only if the try block was successful; this code\n","goes in the else block. The except block tells Python what to do in case a\n","certain exception arises when it tries to run the code in the try block.\n","\n","By anticipating likely sources of errors, you can write robust programs\n","that continue to run even when they encounter invalid data and missing\n","resources. Your code will be resistant to innocent user mistakes and malicious attacks."],"metadata":{"id":"qnFdqlS9io20"}},{"cell_type":"markdown","source":["### Handling the FileNotFoundError Exception\n","One common issue when working with files is handling missing files. The\n","file you’re looking for might be in a different location, the filename may\n","be misspelled, or the file may not exist at all. You can handle all of these\n","situations in a straightforward way with a try-except block.\n","Let’s try to read a file that doesn’t exist. The following program tries\n","to read in the contents of Alice in Wonderland, but I haven’t saved the file\n","alice.txt in the same directory as alice.py"],"metadata":{"id":"39gXQKmyjBNl"}},{"cell_type":"code","source":["filename = 'alice.txt'\n","\n","with open(filename, encoding='utf-8') as f:\n"," contents = f.read()"],"metadata":{"id":"Z0Epow7xjFoR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["There are two changes here. One is the use of the variable f to represent the file object, which is a common convention. The second is the use of\n","the encoding argument. This argument is needed when your system’s default\n","encoding doesn’t match the encoding of the file that’s being read.\n","\n","Python can’t read from a missing file, so it raises an exception:\n","```\n","Traceback (most recent call last):\n"," File \"alice.py\", line 3, in <module>\n"," with open(filename, encoding='utf-8') as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'alice.txt'\n","```\n","The last line of the traceback reports a FileNotFoundError: this is the\n","exception Python creates when it can’t find the file it’s trying to open.\n","\n","In this example, the open() function produces the error, so to handle it, the\n","try block will begin with the line that contains open():"],"metadata":{"id":"AlCJfMJKjJpH"}},{"cell_type":"code","source":["filename = 'alice.txt'\n","\n","try:\n","  with open(filename, encoding='utf-8') as f:\n","    contents = f.read()\n","except FileNotFoundError:\n"," print(f\"Sorry, the file {filename} does not exist.\")"],"metadata":{"id":"7YdrP0-fjZmo"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["In this example, the code in the try block produces a FileNotFoundError,\n","so Python looks for an except block that matches that error. Python then\n","runs the code in that block, and the result is a friendly error message\n","instead of a traceback:\n","```\n","Sorry, the file alice.txt does not exist.\n","```\n","The program has nothing more to do if the file doesn’t exist, so the\n","error-handling code doesn’t add much to this program. Let’s build on this\n","example and see how exception handling can help when you’re working\n","with more than one file.\n"],"metadata":{"id":"UWIr0TrjjfZn"}},{"cell_type":"markdown","source":["### Analyzing Text\n","You can analyze text files containing entire books. Many classic works of literature are available as simple text files because they are in the public domain.\n","The texts used in this section come from Project Gutenberg (http://gutenberg\n",".org/). Project Gutenberg maintains a collection of literary works that are\n","available in the public domain, and it’s a great resource if you’re interested\n","in working with literary texts in your programming projects.\n","\n","Let’s pull in the text of Alice in Wonderland and try to count the number\n","of words in the text. We’ll use the string method split(), which can build a\n","list of words from a string. Here’s what split() does with a string containing\n","just the title \"Alice in Wonderland\":\n","```\n","title = \"Alice in Wonderland\"\n","print(title.split())\n","['Alice', 'in', 'Wonderland']\n","```\n","The split() method separates a string into parts wherever it finds a\n","space and stores all the parts of the string in a list. The result is a list of\n","words from the string, although some punctuation may also appear with\n","some of the words. To count the number of words in Alice in Wonderland,\n","we’ll use split() on the entire text. Then we’ll count the items in the list to\n","get a rough idea of the number of words in the text:"],"metadata":{"id":"ziLzUlYVjmRT"}},{"cell_type":"code","source":["filename = 'alice.txt'\n","\n","try:\n","   with open(filename, encoding='utf-8') as f:\n","      contents = f.read()\n","except FileNotFoundError:\n","    print(f\"Sorry, the file {filename} does not exist.\")\n","else:\n"," # Count the approximate number of words in the file.\n","    words = contents.split()    #1\n","    num_words = len(words)    #2\n","    print(f\"The file {filename} has about {num_words} words.\")    #3"],"metadata":{"id":"z2n_Iqudj0XJ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["I moved the file alice.txt to the correct directory, so the try block will\n","work this time. At **#1** we take the string contents, which now contains the\n","entire text of Alice in Wonderland as one long string, and use the split()\n","method to produce a list of all the words in the book. When we use len() on\n","this list to examine its length, we get a good approximation of the number\n","of words in the original string **#2**. At **#3** we print a statement that reports\n","how many words were found in the file. This code is placed in the else block\n","because it will work only if the code in the try block was executed successfully. The output tells us how many words are in alice.txt:\n","```\n","The file alice.txt has about 29465 words.\n","```\n","The count is a little high because extra information is provided by the\n","publisher in the text file used here, but it’s a good approximation of the\n","length of Alice in Wonderland."],"metadata":{"id":"_OP2u2PkkI-P"}},{"cell_type":"markdown","source":["### Working with Multiple Files\n","Let’s add more books to analyze. But before we do, let’s move the bulk of\n","this program to a function called count_words(). By doing so, it will be easier\n","to run the analysis for multiple books:"],"metadata":{"id":"bpaQghgFkXjt"}},{"cell_type":"code","source":["def count_words(filename):\n"," \"\"\"Count the approximate number of words in a file.\"\"\"    #1\n"," try:\n","    with open(filename, encoding='utf-8') as f:\n","      contents = f.read()\n"," except FileNotFoundError:\n","    print(f\"Sorry, the file {filename} does not exist.\")\n"," else:\n","    words = contents.split()\n","    num_words = len(words)\n","    print(f\"The file {filename} has about {num_words} words.\")\n","\n","filename = 'alice.txt'\n","count_words(filename)"],"metadata":{"id":"rJ0Ngi3FkZJl"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Most of this code is unchanged. We simply indented it and moved it\n","into the body of count_words(). It’s a good habit to keep comments up to date\n","when you’re modifying a program, so we changed the comment to a docstring and reworded it slightly **#1**.\n","\n","Now we can write a simple loop to count the words in any text we want\n","to analyze. We do this by storing the names of the files we want to analyze\n","in a list, and then we call count_words() for each file in the list. We’ll try to\n","count the words for Alice in Wonderland, Siddhartha, Moby Dick, and Little\n","Women, which are all available in the public domain. I’ve intentionally left\n","siddhartha.txt out of the directory containing word_count.py, so we can see\n","how well our program handles a missing file:"],"metadata":{"id":"NLzckjOHklhk"}},{"cell_type":"code","source":["def count_words(filename):\n","  --snip--\n","\n","filenames = ['alice.txt', 'siddhartha.txt', 'moby_dick.txt', 'little_women.txt']\n","for filename in filenames:\n","    count_words(filename)"],"metadata":{"id":"Nf7GZRg_ktow"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["The missing siddhartha.txt file has no effect on the rest of the program’s\n","execution:\n","```\n","The file alice.txt has about 29465 words.\n","Sorry, the file siddhartha.txt does not exist.\n","The file moby_dick.txt has about 215830 words.\n","The file little_women.txt has about 189079 words.\n","```\n","Using the try-except block in this example provides two significant\n","advantages. We prevent our users from seeing a traceback, and we let the\n","program continue analyzing the texts it’s able to find. If we don’t catch\n","the FileNotFoundError that siddhartha.txt raised, the user would see a full\n","traceback, and the program would stop running after trying to analyze\n","Siddhartha. It would never analyze Moby Dick or Little Women."],"metadata":{"id":"wQexzBeSkztL"}},{"cell_type":"markdown","source":["### Failing Silently\n","In the previous example, we informed our users that one of the files\n","was unavailable. But you don’t need to report every exception you catch.\n","Sometimes you’ll want the program to fail silently when an exception occurs\n","and continue on as if nothing happened. To make a program fail silently, you\n","write a try block as usual, but you explicitly tell Python to do nothing in the\n","except block. Python has a pass statement that tells it to do nothing in a block:"],"metadata":{"id":"EV0Jzsu7k5tr"}},{"cell_type":"code","source":["def count_words(filename):\n","    \"\"\"Count the approximate number of words in a file.\"\"\"\n","    try:\n","        --snip--\n","    except FileNotFoundError:\n","        pass    #1\n","    else:\n","        --snip--\n","\n","filenames = ['alice.txt', 'siddhartha.txt', 'moby_dick.txt', 'little_women.txt']\n","for filename in filenames:\n","    count_words(filename)"],"metadata":{"id":"VhoQneiIk8qA"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["The only difference between this listing and the previous one is the\n","pass statement at **#1**. Now when a FileNotFoundError is raised, the code in\n","the except block runs, but nothing happens. No traceback is produced,\n","and there’s no output in response to the error that was raised. Users see\n","the word counts for each file that exists, but they don’t see any indication\n","that a file wasn’t found:\n","```\n","The file alice.txt has about 29465 words.\n","The file moby_dick.txt has about 215830 words.\n","The file little_women.txt has about 189079 words.\n","```\n","The pass statement also acts as a placeholder. It’s a reminder that you’re\n","choosing to do nothing at a specific point in your program’s execution\n","and that you might want to do something there later. For example, in this\n","program we might decide to write any missing filenames to a file called\n","missing_files.txt. Our users wouldn’t see this file, but we’d be able to read\n","the file and deal with any missing texts."],"metadata":{"id":"r8Nq5HGOlNDf"}},{"cell_type":"markdown","source":["### Deciding Which Errors to Report\n","How do you know when to report an error to your users and when to fail\n","silently? If users know which texts are supposed to be analyzed, they might\n","appreciate a message informing them why some texts were not analyzed. If\n","users expect to see some results but don’t know which books are supposed\n","to be analyzed, they might not need to know that some texts were unavailable. Giving users information they aren’t looking for can decrease the\n","usability of your program. Python’s error-handling structures give you finegrained control over how much to share with users when things go wrong;\n","it’s up to you to decide how much information to share.\n","\n","Well-written, properly tested code is not very prone to internal errors,\n","such as syntax or logical errors. But every time your program depends on\n","something external, such as user input, the existence of a file, or the availability of a network connection, there is a possibility of an exception being\n","raised. A little experience will help you know where to include exception\n","handling blocks in your program and how much to report to users about\n","errors that arise"],"metadata":{"id":"JkQ85J-1lViM"}},{"cell_type":"markdown","source":["================================================================================\n","#### **TRY IT YOURSELF**\n","**10-6. Addition**: One common problem when prompting for numerical input\n","occurs when people provide text instead of numbers. When you try to convert\n","the input to an int, you’ll get a ValueError. Write a program that prompts for\n","two numbers. Add them together and print the result. Catch the ValueError if\n","either input value is not a number, and print a friendly error message. Test your\n","program by entering two numbers and then by entering some text instead of a\n","number."],"metadata":{"id":"fScGNg6zlf_D"}},{"cell_type":"code","source":[],"metadata":{"id":"S0s5obkulq_Q"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["**10-7. Addition Calculator**: Wrap your code from Exercise 10-6 in a while loop\n","so the user can continue entering numbers even if they make a mistake and\n","enter text instead of a number.\n"],"metadata":{"id":"n5TFuvR7lrmy"}},{"cell_type":"code","source":[],"metadata":{"id":"D3f0kJJmlvNh"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["**10-8. Cats and Dogs**: Make two files, cats.txt and dogs.txt. Store at least three\n","names of cats in the first file and three names of dogs in the second file. Write\n","a program that tries to read these files and print the contents of the file to the\n","screen. Wrap your code in a try-except block to catch the FileNotFound error,\n","and print a friendly message if a file is missing. Move one of the files to a different location on your system, and make sure the code in the except block\n","executes properly."],"metadata":{"id":"Y4bAquTvlvlC"}},{"cell_type":"code","source":[],"metadata":{"id":"BLpwMXqplzy4"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["**10-9. Silent Cats and Dogs**: Modify your except block in Exercise 10-8 to fail\n","silently if either file is missing."],"metadata":{"id":"eGmAXMggl2nu"}},{"cell_type":"code","source":[],"metadata":{"id":"8CWo3wzyl66e"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["10-10. Common Words: Visit Project Gutenberg (https://gutenberg.org/ )\n","and find a few texts you’d like to analyze. Download the text files for these\n","works, or copy the raw text from your browser into a text file on your\n","computer.\n","\n","You can use the count() method to find out how many times a word or\n","phrase appears in a string. For example, the following code counts the number\n","of times 'row' appears in a string:\n","```\n","line = \"Row, row, row your boat\"\n","print(line.count('row'))\n","2\n","print(line.lower().count('row'))\n","3\n","```\n","Notice that converting the string to lowercase using lower() catches\n","all appearances of the word you’re looking for, regardless of how it’s\n","formatted.\n","\n","Write a program that reads the files you found at Project Gutenberg and\n","determines how many times the word 'the' appears in each text. This will be\n","an approximation because it will also count words such as 'then' and 'there'.\n","Try counting 'the ', with a space in the string, and see how much lower your\n","count is."],"metadata":{"id":"DMD7A8Mvl7c4"}}]}